### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by Juzepe** [kurdin/console-remote-server#1]
I made private remote server on my localhost and I get this error:

`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Can you help me?

**Comment by kurdin** [comment]
@Juzepe Thanks for report, let me try it

**Comment by kurdin** [comment]
@Juzepe  I think I messed up Documentation, did you start your local Server app ? 

run it with:
`npm run server`

then run local console app with 
`npm start`

go to your (any) channel `http://localhost:8090/test-channel` and you should see that console app connected to your server. 

![image](https://user-images.githubusercontent.com/6027060/112499463-dfbb4880-8d5d-11eb-872c-3eb7c5fccef2.png)

You could click `ping` to confirm that your app and server are connected. 

In your JavaScript file `import` or `require`  package `console-remote-client` and use connect method with server option to connect to http://localhost:8088.

https://github.com/kurdin/console-remote-server#a-quick-way-to-connect

I just updated the Documentation for Private Server, please check it again, and let me know if you can connect.

**Comment by Juzepe** [comment]
Now it works. Thank you.
