### ISSUE TITLE
Please provide dockerfiles

### ISSUE THREAD

**Issue by scholz-timo** [kurdin/console-remote-server#10]
Hello console.re team,

I want to deploy your application on my stack, but i dont want to have to manage the dockerfiles (security, updates, etc) on my own.

So i am asking if you could provide and upload some default dockerfiles to the dockerhub.

If you need any assistance in writing theses files, dont hesitate to contact me.

Best Regards,
Timo

**Comment by scholz-timo** [comment]
Ill provide i pull request with some sample dockerfiles, that you can modify to you needs.

**Comment by kurdin** [comment]
> Ill provide i pull request with some sample dockerfiles, that you can modify to you needs.

Yeah, feel free to do a pull request with dockerfile. Unfortunately, I don't have to much time to test it.  Thanks

**Comment by kurdin** [comment]
@yavuzslmtpl Thanks for adding Docker support. I changed few things, I removed NAME and TAG to make it simple and added info on how to run the docker on port 80

https://github.com/kurdin/console-remote-server/tree/main/docker
