### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by scholz-timo** [kurdin/console-remote-server#11]
Hello console.re team,

I want to use this part of your software in a commercial product.
Since your license states that it is only for non commercial use i ask for some kind of agreement so that it is possible to use the console.re server component without re-implementing it.

Best regards,
Timo****

**Comment by kurdin** [comment]
Yeah, you can use it anyway you want. Just add a link to https://github.com/kurdin/console-remote-server

I'll change to MIT. Good luck.
