### ISSUE TITLE
CORS error with private server

### ISSUE THREAD

**Issue by marcotw** [kurdin/console-remote-server#15]
I've configured a private server with all default settings, when I try to connect with my browser client I see this error:

`
Access to XMLHttpRequest at 'http://localhost:3000/socket.io/?EIO=4&transport=polling&t=OiaJH58' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

The server instead show correctly the web page and wait for logs.

**Comment by kurdin** [comment]
@marcotw this is strange because I do set CORS headers in the server code
https://github.com/kurdin/console-remote-server/blob/main/console-server/index.js#L8

but by default, client should be connecting to from localhost:3000 to server's port 8088, please check your .env settings

**Comment by marcotw** [comment]
my env settings (untouched):

```
SERVER_PORT=8088
SERVER_PROTOCOL=http
SERVER_DOMAIN=localhost
APP_PORT=3000
APP_DOMAIN=localhost
APP_CONNECT_HOST=http://localhost:8088
IGNORE_CHANNELS=
```

and my client code:

```
  consolere.connect({
    server: 'http://localhost:3000',
    channel: 'test', // required
    redirectDefaultConsoleToRemote: true, // optional, default: false
    disableDefaultConsoleOutput: true, // optional, default: false
  });
```

**Comment by kurdin** [comment]
When you start the server you should see a port it used. By default, 8088 should be used. In `consolere.connect` you should specify `server: 'http://localhost:8088'`

**Comment by marcotw** [comment]
![image](https://github.com/kurdin/console-remote-server/assets/107467227/11294152-0632-4e52-895c-c1aad3690e28)

This is the log I see when I running the server.

Client side, if I use the port 8088, I see this error in console:

`GET http://localhost:8088/socket.io/?EIO=4&transport=polling&t=OiaXpuv net::ERR_CONNECTION_REFUSED`

With port 3000 instead, the CORS error:

`Access to XMLHttpRequest at 'http://localhost:3000/socket.io/?EIO=4&transport=polling&t=OiaY7XF' from origin 'http://192.168.1.120:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by kurdin** [comment]
Did you run a server ? 

<img width="857" alt="image" src="https://github.com/kurdin/console-remote-server/assets/6027060/f13df701-6b54-4d30-b1db-f3e33b970cc1">

You should run it separately from the client and app and see something like this 

<img width="857" alt="Screenshot 2023-10-12 at 11 44 10" src="https://github.com/kurdin/console-remote-server/assets/6027060/fc14d896-bfa4-4e47-880c-552beb010dec">

**Comment by marcotw** [comment]
My bad, I thought that command `npm run start` runs web app and also the socket server for the communication.
Instead are two separate command to run.

Thank you, sorry for the confusion.
