### ISSUE TITLE
external access

### ISSUE THREAD

**Issue by phatpaul** [kurdin/console-remote-server#16]
I need to expose the server to external hosts, so I changed `SERVER_DOMAIN=localhost` to `SERVER_DOMAIN=0.0.0.0` in env.development.  That allowed remote hosts to connect.  But I found that the console-remote-app when runnning on a remote host is trying to connect to the server at localhost:8088, so I changed it to `APP_CONNECT_HOST=http://192.168.33.75:8088`

```
SERVER_PORT=8088
SERVER_PROTOCOL=http
SERVER_DOMAIN=0.0.0.0
APP_PORT=3000
APP_DOMAIN=0.0.0.0
APP_CONNECT_HOST=http://192.168.33.75:8088
IGNORE_CHANNELS=
```
But now the app will not load. There is this error in the browser: 
```
The script from “http://192.168.33.75:3000/app/js/consoleapp-c506cc93d0.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. poco-console-re
Uncaught SyntaxError: expected expression, got '<' consoleapp-c506cc93d0.js:1:1
Loading failed for the <script> with source “http://localhost:35729/livereload.js?snipver=1”. poco-console-re:612:61
```
It looks like the app server is sending the HTML instead of the javascript when request is view-source:http://192.168.33.75:3000/app/js/consoleapp-c506cc93d0.js

When I revert to `APP_CONNECT_HOST=http://localhost:8088`, the app loads properly again, but of course I can't use it on a host other than the server.

**Comment by phatpaul** [comment]
Update: I did a Shift+reload on the app and it works now.  I guess some cache was stale.  Ugh, that took me too long to figure out.

**Comment by kurdin** [comment]
@phatpaul I started looking at this but glad you figure this out!
