### ISSUE TITLE
Deploy on production using Apache

### ISSUE THREAD

**Issue by Juzepe** [kurdin/console-remote-server#2]
I tried launch on production, but I got error:

`http://www.my-domain/www/css/www-bundle-bf7fd723c9.css net::ERR_ABORTED 404 (Not Found)`

Maybe, it is due to relative paths?

**Comment by kurdin** [comment]
@Juzepe, no path is absolute, it should work, if you look at `build/www/index.html`file you should see link to `/www/css/www-bundle-bf7fd723c9.css` there is something in your webserver config. 
Can you load js files with direct link like `http://www.my-domain/www/js/index-bundle-16773faef7.js` ?

**Comment by Juzepe** [comment]
No, same error.

**Comment by kurdin** [comment]
but you can load and see `www/index.html` when you hit your `http://www.my-domain/` right ?

**Comment by Juzepe** [comment]
Yes.

**Comment by Juzepe** [comment]
As I see `www` is unnecessary? 

`<link rel="stylesheet" href="/www/css/www-bundle.css" />`

**Comment by kurdin** [comment]
Yes, I need that for localhost. Do you use nginx ?

**Comment by Juzepe** [comment]
I use Apache.

**Comment by kurdin** [comment]
oh, ok. I did not use Apache for a long time. Try this 

copy your console server `build` folder to your `/home/www/console/build`
Root of webserver should be in 
`DocumentRoot /home/www/console/build`
but index.html should have path 
`DirectoryIndex /www/index.html` that should be inside `DocumentRoot`

**Comment by kurdin** [comment]
with Nginx, this is a pretty easy to do 

```
root /home/www/console/build;
location / {
          index /www/index.html;
          try_files $uri $uri/ /app/consoleapp.html;
    }
```

**Comment by Juzepe** [comment]
I moved index.html file from `build/www` folder to `build` folder and it works now. :)

But when I go to `http://www.my-domain/my-project` it goes to error: `404 (Not Found)`. As I guess because of Apache.

**Comment by kurdin** [comment]
> But when I go to http://www.my-domain/my-project it goes to error: 404 (Not Found)

This is because in Apache you need to have rewrite rule for any `/url-path` (but static files) to load a html file from `/app/consoleapp.html`

This is how it works on Nginx
`try_files $uri $uri/ /app/consoleapp.html;`

**Comment by kurdin** [comment]
@Juzepe do you have any progress with setting up Apache and console remote server on production ?

**Comment by Juzepe** [comment]
I'm out of town and I will find out soon. Thanks.

**Comment by Juzepe** [comment]
I tried many things without success. Can you give us rights on https://console.re/ to connect from servers also?

As I remember, we had such right.

**Comment by Juzepe** [comment]
I tried rewrite rules, but http://www.my-domain/my-project looks like exactly http://www.my-domain.

**Comment by kurdin** [comment]
>I tried many things without success.

can you install a docker on your server ? I can create a console remote server docker with nginx. 

>Can you give us rights on https://console.re/ to connect from servers also?

Unfortunately I can't, because it quickly gets abused by many many request from different production servers and clients and my server could not keep up with that load.

>I tried rewrite rules, but http://www.my-domain/my-project looks like exactly http://www.my-domain.

that means rewrite rule does not work correctly, it should take any uri like `/my-project` and load static file from `/app/consoleapp.html` and not `index.html`

**Comment by kurdin** [comment]
@Juzepe btw, try to rename `consoleapp.html` to `index.html` and replace your current index with new file. This should work as quick fix.

**Comment by Juzepe** [comment]
I found solution. Inside `Directory` must be:

```RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . app/consoleapp.html [L]```

But I have another problem: `consoleRe [warning] seems like you trying to use console remote on public, production server. Console.Re is for light, local development only, for production you can install and use self hosted solution`. Same as on https://console.re/

**Comment by kurdin** [comment]
`But I have another problem: `consoleRe [warning] seems like you trying to use console remote on public, production server. Console.Re is for light, local development only, for production you can install and use self hosted solution`. Same as on https://console.re/
`

let me check that

**Comment by kurdin** [comment]
@Juzepe did you change connection option `server: 'https://your-remote-console-server-name.com'` ?
did you try connect to your console server from localhost ?

**Comment by Juzepe** [comment]
Now I'm struggling to CORS policy :)

**Comment by kurdin** [comment]
@Juzepe you need to look for Apache CORS solution. Sorry can't help with this.
