### ISSUE TITLE
Watch all channels at once (self-hosted)

### ISSUE THREAD

**Issue by elvendor** [kurdin/console-remote-server#4]
First of all thank you for this great package!
As far as I understand this package supports multitenancy already.
But can we see logs from all channels at once?

**Comment by kurdin** [comment]
@elvendor yes, it supports multi channels, you can output logs to any channels you want and see them separated by channel's name, but you can not see all channels at once in one place. 

What is your use case? why not to connect all your clients to a single `all-in-one-channel` and see logs in one place like `https://your-console.domain.com/all-on-one-channel`

**Comment by elvendor** [comment]
Thanks for the reply.
I have the same app running on a different client domains. I did like like you say but I don't see any sepration by domains in logs.
https://www.papertrail.com does that but only for server.

**Comment by kurdin** [comment]
@elvendor you need to use `connect` method and provide different `channel` names for all your clients separate domains.

You can try to use `window.location.hostname` for channel name to separate by domain hostname where your script is running.

```
import consolere from 'console-remote-client'

consolere.connect({
  server: 'https://your-console-server',
  channel: window.location.hostname,
})
```

**Comment by elvendor** [comment]
Thank you @kurdin !
