### ISSUE TITLE
Can  you write a guide that works with Plesk onyx on linux?

### ISSUE THREAD

**Issue by Pangamma** [kurdin/console-remote-server#9]
Just trying to get this to work with Plesk Onyx, and it would be super awesome if your guides worked well with plesk onyx. Thanks.

**Comment by kurdin** [comment]
I don't have time and I don't use Plesk Onyx. Sorry

**Comment by homemadestea58** [comment]
@Pangamma What are you trying to achieve?

**Comment by Pangamma** [comment]
Well it would be super cool to be able to have this console logging on my Linux server, but Plesk does not allow you to modify the root location in the nginx configuration file. Also, it has an application for running node apps but need to figure out how to set that up and which settings to give it. That's what I was trying to accomplish. I eventually gave up.

**Comment by homemadestea58** [comment]
@Pangamma Why do you need this logging? Can't you just view or tail the logs directly on the server?

I'm just trying to make sure that you get what you need and aren't wasting your own time.

**Comment by Pangamma** [comment]
The whole point of this is to log front end client sided console logs right?

**Comment by kurdin** [comment]
> 



> The whole point of this is to log front end client sided console logs right?

Well, you can use it on server with CLI to send logs to your consolere remote sever 

`npm install console-remote-client -g`

`consolere -c YOUR-CHANNEL-NAME log 'sent from command line' `

but I would not recommend to use it that way

**Comment by futureweb** [comment]
@Pangamma  - did you find a way to run it on Plesk? I'm currently also looking into this.

**Comment by kurdin** [comment]
@futureweb if you don't have root shell access I don't think you can install in via Plesk UI. If you have shell root access, install dockers and use this guide to run it as a docker https://github.com/kurdin/console-remote-server/tree/main/docker

**Comment by futureweb** [comment]
Hi @kurdin,

Thanks for your prompt response. I was wondering if there's a possibility for you to publish the Docker image on "Docker Hub"? This would enable anyone to easily run the console-remote-server on Plesk using Docker, as described here: https://docs.plesk.com/en-US/obsidian/administrator-guide/plesk-administration/using-docker.75823/

This would be a significant improvement in the accessibility of this **great tool**!

Thank you,
Andy

**Comment by futureweb** [comment]
@kurdin - nice, thx! 👍🏻

https://hub.docker.com/r/yavuzslmtpl/console-remote-server
